export enum AccountType {
  MEMBER = 'MEMBER',
  STAFF = 'STAFF',
}

export enum Language {
  AR = 'ar',
  EN = 'en',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

/** Canonical default role keys. Authorization is by permission, not role name. */
export enum RoleKey {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  RECEPTIONIST = 'RECEPTIONIST',
  ACCOUNTANT = 'ACCOUNTANT',
}

export enum SubscriptionStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAYMENT_UNDER_REVIEW = 'PAYMENT_UNDER_REVIEW',
  ACTIVE = 'ACTIVE',
  EXPIRING_SOON = 'EXPIRING_SOON',
  EXPIRED = 'EXPIRED',
  FROZEN = 'FROZEN',
  CANCELLED = 'CANCELLED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  FAKE = 'FAKE',
  CANCELLED = 'CANCELLED',
  REFUND_REQUESTED = 'REFUND_REQUESTED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentMethodType {
  INSTAPAY = 'INSTAPAY',
  VODAFONE_CASH = 'VODAFONE_CASH',
  MOBILE_WALLET = 'MOBILE_WALLET',
  BANK_TRANSFER = 'BANK_TRANSFER',
  OTHER = 'OTHER',
}

export enum SubscriptionFreezeStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum AccessDecision {
  APPROVED = 'APPROVED',
  DENIED_INVALID = 'DENIED_INVALID',
  DENIED_EXPIRED = 'DENIED_EXPIRED',
  DENIED_FROZEN = 'DENIED_FROZEN',
  DENIED_NO_MEMBERSHIP = 'DENIED_NO_MEMBERSHIP',
  DENIED_PENDING_PAYMENT = 'DENIED_PENDING_PAYMENT',
  DENIED_DAILY_LIMIT = 'DENIED_DAILY_LIMIT',
  ALREADY_CHECKED_IN = 'ALREADY_CHECKED_IN',
}

export enum AttendanceSource {
  QR_CAMERA = 'QR_CAMERA',
  QR_SCANNER = 'QR_SCANNER',
  MANUAL = 'MANUAL',
}

export enum NotificationType {
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_ACTIVATED = 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_EXPIRING = 'SUBSCRIPTION_EXPIRING',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_FROZEN = 'SUBSCRIPTION_FROZEN',
  PAYMENT_SUBMITTED = 'PAYMENT_SUBMITTED',
  PAYMENT_APPROVED = 'PAYMENT_APPROVED',
  PAYMENT_REJECTED = 'PAYMENT_REJECTED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  QR_ISSUED = 'QR_ISSUED',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  PROMOTION = 'PROMOTION',
  SYSTEM = 'SYSTEM',
}

export enum WhatsAppTemplateKey {
  EXPIRY_REMINDER = 'EXPIRY_REMINDER',
  EXPIRED = 'EXPIRED',
  PAYMENT_REMINDER = 'PAYMENT_REMINDER',
  PAYMENT_APPROVED = 'PAYMENT_APPROVED',
  PAYMENT_REJECTED = 'PAYMENT_REJECTED',
  WELCOME = 'WELCOME',
  RENEWAL = 'RENEWAL',
  OFFER = 'OFFER',
}

export enum MessageChannel {
  WHATSAPP_MANUAL = 'WHATSAPP_MANUAL',
  WHATSAPP_API = 'WHATSAPP_API',
}

export enum MessageLogStatus {
  GENERATED = 'GENERATED',
  OPENED = 'OPENED',
  SENT = 'SENT',
  FAILED = 'FAILED',
}

export enum MediaResourceType {
  IMAGE = 'image',
  VIDEO = 'video',
  RAW = 'raw',
}

export enum MediaFolder {
  CMS = 'cms',
  MEMBERS = 'members',
  PAYMENT_PROOFS = 'payment-proofs',
  BRANDING = 'branding',
}

export enum CmsSectionType {
  HERO = 'HERO',
  STATS = 'STATS',
  ABOUT_PREVIEW = 'ABOUT_PREVIEW',
  MEMBERSHIP_PLANS = 'MEMBERSHIP_PLANS',
  FACILITIES = 'FACILITIES',
  WHY_US = 'WHY_US',
  TRAINING_EXPERIENCE = 'TRAINING_EXPERIENCE',
  TRAINERS = 'TRAINERS',
  TESTIMONIALS = 'TESTIMONIALS',
  FAQ = 'FAQ',
  CTA = 'CTA',
  LOCATION = 'LOCATION',
  RICH_TEXT = 'RICH_TEXT',
}

export enum AuditAction {
  MEMBER_UPDATED = 'MEMBER_UPDATED',
  MEMBER_CREATED = 'MEMBER_CREATED',
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_RENEWED = 'SUBSCRIPTION_RENEWED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_FROZEN = 'SUBSCRIPTION_FROZEN',
  SUBSCRIPTION_UNFROZEN = 'SUBSCRIPTION_UNFROZEN',
  PAYMENT_SUBMITTED = 'PAYMENT_SUBMITTED',
  PAYMENT_APPROVED = 'PAYMENT_APPROVED',
  PAYMENT_REJECTED = 'PAYMENT_REJECTED',
  PAYMENT_MARKED_FAKE = 'PAYMENT_MARKED_FAKE',
  PAYMENT_CANCELLED = 'PAYMENT_CANCELLED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  QR_ISSUED = 'QR_ISSUED',
  QR_BATCH_GENERATED = 'QR_BATCH_GENERATED',
  QR_ASSIGNED = 'QR_ASSIGNED',
  QR_UNASSIGNED = 'QR_UNASSIGNED',
  QR_REGENERATED = 'QR_REGENERATED',
  QR_REVOKED = 'QR_REVOKED',
  CMS_UPDATED = 'CMS_UPDATED',
  MEDIA_DELETED = 'MEDIA_DELETED',
  ROLE_CHANGED = 'ROLE_CHANGED',
  STAFF_UPDATED = 'STAFF_UPDATED',
  SETTINGS_UPDATED = 'SETTINGS_UPDATED',
  ATTENDANCE_CREATED = 'ATTENDANCE_CREATED',
}
